[package]
name = "runx"
version = "0.0.0"
edition = "2024"
default-run = "runx"

[dependencies]
anyhow = "1.0"
base64 = "0.22"
directories = "6.0"
global-hotkey = "0.7"
image = { version = "0.25", default-features = false, features = ["png", "webp"] }
memchr = "2.7"
miette = { version = "7.6", features = ["fancy"] }
mlua = { version = "0.11.6", features = ["lua55", "send", "serde", "vendored"] }
plist = "1.7"
png = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shell-words = "1.1"
tempfile = "3.27"
thread_local = "1.1"
time = { version = "0.3", features = ["formatting"] }
tokio = { version = "1.48", features = ["rt-multi-thread", "time"] }
toml = "0.8"
toml_edit = "0.23.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
walkdir = "2.5"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10"
core-foundation-sys = "0.8"
core-graphics = "0.25"
objc2 = "0.6"
objc2-app-kit = { version = "0.3.2", features = ["NSApplication", "NSBitmapImageRep", "NSGraphics", "NSGraphicsContext", "NSImage", "NSImageRep", "NSPasteboard", "NSRunningApplication", "NSScreen", "NSWorkspace", "libc"] }
objc2-foundation = { version = "0.3.2", features = ["NSError", "NSProcessInfo", "NSString", "NSURL", "NSValue"] }
objc2-service-management = "0.3.2"
tao = "0.35"
tray-icon = "0.21"
wry = { version = "0.55", features = ["transparent"] }

[patch.crates-io]
tao = { git = "https://github.com/sloppish/tao.git", rev = "c355c45d1323721e759eb7c3dde3fb9533b04e09" }

[lints.rustdoc]
broken_intra_doc_links = "deny"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
